# Generated by Django 5.2.7 on 2025-12-21 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_note_is_deleted'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='note',
            options={'ordering': ['order', '-created_at']},
        ),
        migrations.AddField(
            model_name='note',
            name='order',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
    ]
