# Generated by Django 5.2.7 on 2025-11-06 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0003_alter_note_options_note_is_public_alter_note_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='note',
            old_name='is_public',
            new_name='is_private',
        ),
        migrations.AlterField(
            model_name='note',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
    ]
