# Generated by Django 5.2.7 on 2025-11-09 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0004_rename_is_public_note_is_private_alter_note_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='category',
            field=models.CharField(choices=[('GEN', 'General'), ('IMP', 'Important'), ('TODO', 'To Do'), ('IDE', 'Idea')], default='GEN', max_length=4),
        ),
    ]
