# Generated by Django 5.2.7 on 2025-12-24 13:27

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0006_note_is_shared_note_share_uuid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='note',
            old_name='is_private',
            new_name='is_public',
        ),
        migrations.RemoveField(
            model_name='note',
            name='is_shared',
        ),
        migrations.AlterField(
            model_name='note',
            name='share_uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
